# Generated by Django 4.1.7 on 2023-02-28 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('feature_image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('description', models.TextField()),
                ('department', models.CharField(choices=[('Construction', 'Construction'), ('RealEstate', 'Realestate'), ('Health Care', 'Health Care'), ('Import/Export', 'Import/Export'), ('Technology', 'Technology'), ('Utility', 'Utility'), ('Other', 'Other')], max_length=200)),
                ('risk', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Unknown', 'Unknown')], max_length=200)),
                ('expected_Return', models.CharField(choices=[('Construction', 'Construction'), ('RealEstate', 'Realestate'), ('10%<##>30%', '10%<##>30%'), ('30%<##>50%', '30%<##>50%'), ('50%<##>70%', '50%<##>70%'), ('70%<##', '70%<##'), ('Other', 'Other')], max_length=200)),
                ('established_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usrs')),
            ],
        ),
    ]
