# Generated by Django 4.1.7 on 2023-03-01 08:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_project_sharescount_project_sharesvalue_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usrs',
            new_name='Users',
        ),
        migrations.RemoveField(
            model_name='shares',
            name='user',
        ),
    ]
