# Generated by Django 4.1.7 on 2023-03-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_shares_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='blance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
